["/my_command"]
case_sensitive = false
reply = true
ignore_formatters_errors = true
ignore_hooks_errors = true
react_on_me = false
react_on_others = false
response_text = "ответ на команду"
hooks = []
