["/my_command"]
case_sensitive = false
reply = true
abort_on_formatters_error = false
abort_on_hooks_error = false
react_on_me = true
react_on_others = false
response_text = "Текущее время: $time<%H:%M>"
hooks = []
