["/my_command"]
case_sensitive = false
reply = false
abort_on_formatters_error = false
abort_on_hooks_error = true
react_on_me = false
react_on_others = false
response_text = "Текущее время: $time<datetime>"
hooks = []
